# Generated by Django 4.0.5 on 2023-03-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Witness_Name', models.CharField(max_length=100)),
                ('Witness_Email', models.EmailField(max_length=254)),
                ('Witness_Phone', models.CharField(blank=True, max_length=17, null=True)),
                ('Date_of_accident', models.DateField()),
                ('Time_of_accident', models.DateTimeField()),
                ('is_vital', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
            ],
        ),
    ]
