# Generated by Django 4.0.5 on 2023-03-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Gender_Witness',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='report',
            name='Location',
            field=models.CharField(choices=[('Alimosho', 'Alimosho'), ('Agege', 'Agege')], default='Agege', max_length=20),
        ),
    ]
